name: CI Pipeline

on:
  push:
    branches: [ main ]   # run tests when you push to main
  pull_request:          # also run on PRs

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt   # 👈 use requirements.txt

    - name: Run tests
      run: pytest
